// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230712043636_AddDataTableVilla")]
    partial class AddDataTableVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SquareMeter")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            Created_at = new DateTime(2023, 7, 12, 4, 36, 36, 480, DateTimeKind.Utc).AddTicks(8304),
                            Description = "Test",
                            ImageUrl = "",
                            Name = "Test",
                            Occupants = 3,
                            Price = 3000.0,
                            SquareMeter = 3,
                            Updated_at = new DateTime(2023, 7, 12, 4, 36, 36, 480, DateTimeKind.Utc).AddTicks(8305)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            Created_at = new DateTime(2023, 7, 12, 4, 36, 36, 480, DateTimeKind.Utc).AddTicks(8307),
                            Description = "Test2",
                            ImageUrl = "",
                            Name = "Test2",
                            Occupants = 3,
                            Price = 3000.0,
                            SquareMeter = 3,
                            Updated_at = new DateTime(2023, 7, 12, 4, 36, 36, 480, DateTimeKind.Utc).AddTicks(8307)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
